Tache/urls.py
from django.urls import path
from Tache.views import TacheDeleteView, TacheDetailView, TacheListView

app_name = "tache"
urlpatterns = [
    path("tache_list/", TacheListView.as_view(), name="tache_list"),
    path("tache_detail/<int:pk>/", TacheDetailView.as_view(), name="tache_detail"),
    path("tache_delete/<int:pk>/", TacheDeleteView.as_view(), name="tache_delete"),
]

compte/urls.py
from django.urls import path
from compte import views

app_name="compte"
urlpatterns = [
      path("register/", views.user_registration_view, name="register"),
      path("connecter/", views.user_login_view, name="connecter")
]

pages/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = "page"
urlpatterns = [
  
    path('',home_view,name='home'),
    path('contact',contact_view,name='contact'),
    path('about',about_view,name='about'),
    path('details',detail_view,name='details'),
    path('all',all_view,name='all'),
    path('create_produit',produit_create_view,name='create_produit'),
    path("produit/detail/<int:id>/", produit_details_view, name="produit_details_view"),
    path("produit/delete/<int:id>/", produit_delete_view, name="produit_delete_view"),
]

test1/urls.py
from django.contrib import admin
from django.urls import include, path


admin.site.site_header = "Admin q",
admin.site.site_title = "TEST" ,
# admin.site.site_url = "TEST"
admin.site.index_title =  "TEST"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('pages.urls')) , 
    path('cours/' , include('cours.urls')) , 
    path('tache/' , include('Tache.urls')) , 
    path('compte/' , include('compte.urls')) , 
]

templates/about.html
{% extends 'base.html' %}

{% block title %}
       About
{% endblock title %}
    {% load static %}
{% block content %}
       <h1>Page d'about</h1>
       <img src="{% static 'images/R_11.jpeg' %}" alt="" width="100px" height="100px" srcset="">
{% endblock content %}
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
        
    {% endblock title %}


    
        </title>

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        
        {% block css %}
          
        {% endblock css %}
          
</head>
<body>
      <h2>{{request.user}}</h2>
      <header>
        <nav>
            <ul>
              <li><a href="{% url 'compte:register' %}">Registration</a></li>
              <li><a href="{% url 'compte:connecter' %}">connexion</a></li>
                <li><a href="/">Home</a></li>
                <li><a href="contact">Contact</a></li>
                <li><a href="about">About</a></li>
                <li><a href="{% url 'page:details' %}">Detail</a></li>
                <li><a href="{% url 'page:all' %}">All</a></li>
                <li><a href="create_produit">Créer un produit</a></li>
            </ul>
        </nav>
      </header>
      
   
        {% comment %} {% if messages %}
            
            {% for messages in message %}
                 <p class="alert alert-{{message.tags}}">{{message}}</p>
            {% endfor %}
             
        {% endif %}
          {% endcomment %}
         
    
      <main>
        {% block content %}
           
        {% endblock content %}
      </main>
      
      <footer>
        
      </footer>
   <script src="{% static 'js/index.js' %}"></script>     
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}
       Contact
{% endblock title %}
    
{% block content %}
       <h1>Page de Contact</h1>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
       Home
{% endblock title %}
    
{% block content %}


{% if request.user.is_authenticated %}
         <h1>{{request.user.email }}</h1>
{% else %}
         <h1>Hello guest</h1>
{% endif %}


{% if liste %}
<ul>
         {% for item in liste %}
                 
                     <li>{{forloop.counter }} - {{item}}</li>
              
         {% endfor %}
       </ul>           
{% endif %}
       
       
       <h1>Page d'accueil {{ user }} </h1>
{% endblock content %}
    